version: '3.8'

services:
  backend:
    image: interests/ml-capstone-traffic-sign-recognition-backend:latest
    ports:
      - "8080:8080"
    networks:
      - gtsrb-network

  frontend:
    image: interests/ml-capstone-traffic-sign-recognition-frontend:latest
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - gtsrb-network

networks:
  gtsrb-network:
    driver: bridge